[project]
name = "bear-lake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.36.1",
]

[dependency-groups]
dev = [
    "yfinance>=1.0",
]
